### ISSUE TITLE
Laboratorio - Busqueda

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#10]
en estos campos de abajo no me deja escribir, solo seleccionar... 
lo cual no esta tan mal, pero no me da eleccion a las capturas que hice... antes!!
por ejemplo: Area/producto, habia puesto BCHE<BSUP<SUELO....
![image](https://user-images.githubusercontent.com/28766240/31415643-73b61c30-add9-11e7-90bd-6c1ce02ecf2c.png)

**Comment by delcabo** [comment]
en ZONA si me da los que puse antes

**Comment by caom92** [comment]
No le va dar a elegir hasta que seleccione una Zona, recuerde que la jerarquía es: 
1. Zona
2. Rancho
3. Productor
4. Área o Producto

La jerarquía es líneal, lo que significa que productor depende de rancho, rancho de zona, etc. Por eso al principio no le va a dar opciones para ningún campo mas que para zonas; debe elegir 1ro una zona para que se cargue la lista de ranchos, luego elije un rancho para que se cargue la lista de productor y así sucesivamente. Si no elije nada el sistema no tiene ninguna forma de saber qué datos mostrar en esa lista y tampoco puede simplemente mostrarlos todos porque sería una lista demasiado larga.

**Comment by delcabo** [comment]
Ok entiendo pero si quiero buscar los BCHE de BCN  como le hago

**Comment by caom92** [comment]
Primero elije BCN, eso hará que le aparezca lista en la parte de Ranchos, luego elije un rancho y eso hará que le aparezca la lista de Productores, luego elije un productor y eso hará que aparezca la lista de Áreas o Producto

**Comment by delcabo** [comment]
Hola Carlos, haciendo este metodo, esta bien cuando quiero todo de todo, pero por ejemplo no me deja seleccionar nada en  productor o Areas  solo sale  ALL-TODOS
![image](https://user-images.githubusercontent.com/28766240/31453802-32d7d4c6-ae68-11e7-958c-f6a572b11f0d.png)

**Comment by delcabo** [comment]
curioso el dato, Sale solamente MICROBIOLOGICO PATOGENO, aun cuando el primero registro de eta muestra es MULTI RESIDUOS PLAGUICIDA

![image](https://user-images.githubusercontent.com/28766240/32074738-3ff5f226-ba4f-11e7-982d-6c6f3be851de.png)

**Comment by delcabo** [comment]
Buenas tardes

De nuevo cambio todos los analisi a MICROBIOLOGICO PATOGENO!! :(
![image](https://user-images.githubusercontent.com/28766240/32465035-f30be0dc-c2f6-11e7-93f7-da5056821fdb.png)
