### ISSUE TITLE
en la Captura de Documento con nuevo se queda ciclado...

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#11]
se queda ciclado...  di de alta un nuevo DOCUMENTO "PROCEDIMIENTO SOP"
intente capturarlo y nada  ,   se hizo prueba con otro documento ya existente y si se envio bien...

![image](https://user-images.githubusercontent.com/28766240/31798163-1573764e-b4e7-11e7-9d48-b64359c02e80.png)

**Comment by VMiracle** [comment]
Por lo que entiendo, es al momento de enviar la captura que se presenta el error, revisaremos qué sucede en ese caso

Como detalle adicional, cuando la red se encuentra lenta y una llamada a un servicio llega a timeout, el modal no se cierra y se queda colgado como en la captura; una posible solución será cerrar el modal cuando esto suceda y notificarle al usuario para que sepa qué sucedio y sugerirle que recargue la página

**Comment by caom92** [comment]
El usuario ya no puede agregar nuevos documentos para su captura
