### ISSUE TITLE
No da opcion de escritura y/o opciones de seleccion

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#12]
en el campo de zona no deja escribir nada y/o no salen opciones de seleccion
y por ende no deja registrar nada

![image](https://user-images.githubusercontent.com/28766240/31853082-f60020b2-b637-11e7-8d41-9c59429c9143.png)

**Comment by caom92** [comment]
El servidor no estaba bien configurado para responder a las peticiones recibidas por la aplicación. Ya lo corregí.
