### ISSUE TITLE
No salen registros en busqueda

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#13]
al momento de captura de registros todo indica normal o sin ningun mensaje que si o que no se fue el registro...
y  cuando buscais el registro no salen encontrados...
![image](https://user-images.githubusercontent.com/28766240/31909887-74948abc-b7f0-11e7-9a06-8519a7641a36.png)

**Comment by caom92** [comment]
Era un error en la captura de documentos, ya quedo arreglado
