### ISSUE TITLE
USER login se queda pegado...

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#14]
cuando entras desde Manual como Yaneth, todo bien
te metes a Documento como Yaneht, todo bien

pero sales y cambias de Usuario a Sonia, todo bien
Entras a Docuemnt y se queda Yaneth logeed in..

**Comment by caom92** [comment]
Ya le había explicado que esto iba a ocurrir. Eso es porque la sesión en ambos sistemas es INDEPENDIENTE el uno del otro. Recuerde que habíamos decidido implementarlo así porque iba a ser el camino más rápido. Si desea que la sesión de ambos sistemas esté unida como si se tratara de una sola, necesitare alrededor de un mes para poder implementarlo.
