### ISSUE TITLE
Buscar Documento

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#15]
Si el orden en el reporte puede ser el siguiente:
Fecha, Zona, UP, Loboratrio, Tipo, Sub Tipo, Area...

y si es posible un poco mas estrecho los campos y tal vez quepa en rango HORIZONTAL...

![image](https://user-images.githubusercontent.com/28766240/31966261-f20dcc1e-b8be-11e7-8318-d2c1b5c44dfa.png)

**Comment by caom92** [comment]
No se puede ajustar el ancho de la tabla para que se vean todas las columnas en la pantalla. Ya había explicado anteriormente que son demasiadas columnas y además el contenido de cada columna es muy largo, particularmente la fecha, el tipo de análisis y el área/producto. Si hago la tabla más angosta, la información de estos campos se va a cortar en varios renglones haciendo que la tabla sea más difícil de comprender.

Fuera de eso, los demás cambios ya están implementados.
