### ISSUE TITLE
Reporte Mapeo

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#16]
Veo que falto el campo de Sub Tipo (todos o la seleccion)

![image](https://user-images.githubusercontent.com/28766240/32064684-6c4cf934-ba2f-11e7-85cf-2e5da70978d4.png)

o si es mas facil dejar como esta y que en el reporte salga separado o cortado por el Sub Tipo:

Microbiologico Patogeno:
           Producto de Campo:
                          Tomates Cherry
                           Pepinos...
           Producto Lavado:
                           Tomates Cherry
                           Pepinos...

**Comment by caom92** [comment]
Acabo de subir una versión nueva a su servidor; la tabla ahora agrupa los resultados por subtipo de la siguiente forma: 

![screenshot_2017-10-26_17-01-53](https://user-images.githubusercontent.com/9997614/32082508-dd180c1c-ba70-11e7-9728-8248423e6d2a.png)

Sin embargo, para lograr este diseño tuve que sacrificar ciertas capacidades de esa tabla. En la versión anterior, esa tabla se ajustaba al tamaño de la pantalla para que los datos pudieran ser legibles aún cuando se estaban viendo en una pantalla muy pequeña. Esto lo lograba reacomodando los datos cuando detectaba cuando la pantalla era muy angosta, como se puede ver en las siguientes imágenes de ejemplo:

### Tabla responsiva cuando la pantalla es ancha:
![screenshot_2017-10-26_17-09-51](https://user-images.githubusercontent.com/9997614/32082543-30f03b34-ba71-11e7-8f26-15496de80d45.png)

### Tabla responsiva cuando la pantalla es angosta:
![screenshot_2017-10-26_17-11-17](https://user-images.githubusercontent.com/9997614/32082538-28908a3e-ba71-11e7-8948-8697b5ef31b1.png)

Pero para lograr agrupar los renglones de la tabla, similar a como se puede hacer en Excel, tuve que quitarle esa característica porque rompe el funcionamiento de la tabla responsiva. Así que ahora, sin importar el tamaño de la pantalla, la tabla se desplegará siempre igual: 

![screenshot_2017-10-26_17-16-07](https://user-images.githubusercontent.com/9997614/32082603-99e30ffe-ba71-11e7-97ef-d3a04bf9d533.png)

**Comment by delcabo** [comment]
ya no saca MAPEO por fechas solamente.... aunq cuando le pongo ZONA no deja sacar reporte!!!

lo ideal del mapa es por fecha y zona... (ue incluya todos los tipos de analisis, sub analisis y areas)

![image](https://user-images.githubusercontent.com/28766240/32200946-76a5d224-bd91-11e7-80a5-6b7bbe825f07.png)

**Comment by delcabo** [comment]
tenemos algo al respecto de este detalle??
antes solo era las fechas y la zona....

a menos quepongamos la opcion de TODOS en Tipo y subTipo?

![image](https://user-images.githubusercontent.com/28766240/32306164-ff78d686-bf36-11e7-983a-98d25fc659c5.png)
