### ISSUE TITLE
Buscador se queda ciclado...

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#17]
Mensaje dentro de   NETWORK - Search-LAB

"<b>Fatal error</b>:  Call to undefined method DataBase\Fsm\Zones::getNameByID() in <b>/home1/juliol2j/public_html/documents/backend/services/lab/search-lab.php</b> on line <b>79</b><br />"

![image](https://user-images.githubusercontent.com/28766240/32128571-ac96efe0-bb33-11e7-9bd7-a75be9270b32.png)

**Comment by caom92** [comment]
Era una hoja de código que no estaba actualizada, ya quedo arreglado
