### ISSUE TITLE
Tipo de Analisis pegado!!! 

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#18]
En el reporte de LABORATORIO todos los registros salen tipo de analisis MICROBIOLOGICO PATOGENO aun cuando se captruaron de otro tipo.

![image](https://user-images.githubusercontent.com/28766240/32200762-81b92432-bd90-11e7-89c0-267e01d53135.png)

**Comment by caom92** [comment]
Realicé varias capturas de prueba y no tuve problemas con ninguna; se capturaron correctamente con el tipo que les correspondia y cuando realizo una búsqueda, me muestra el tipo correcto. Igual subí una versión nueva donde posiblemente se arregló el problema.
