### ISSUE TITLE
Boton de regreso a www.manual.....

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#19]
se podra poner botton de link a www.manual.jfdc.tech en:

abajo bien cargado a la derecha a nivel de   "ENTRAR                                              ir a Principal" 

![image](https://user-images.githubusercontent.com/28766240/32306275-9c9a313a-bf37-11e7-9cef-97731c26f828.png)

**Comment by delcabo** [comment]
![image](https://user-images.githubusercontent.com/28766240/32922775-cf422432-cae8-11e7-8085-762390cee20b.png)

**Comment by caom92** [comment]
Ya quedó implementado, quedará en el servidor de Julio en la próxima actualización.
