### ISSUE TITLE
Agregar campos adicionales en la pantalla de captura de documentos

### ISSUE THREAD

**Issue by caom92** [caom92/doc-manager#2]
Julio dijo: 
> me faltaron campos
- [x] Fecha (campo de fecha, ingresado por el usuario) 1
- [ ] Laboratorio (campo abierto de texto)
- [x] Zona (campo de tipo lista de selección, tomado de las Zonas guardadas en el sistema)
- [x] Productor (campo abierto de texto)1
- [ ] Producto o Área (campo abierto de texto)1
- [ ] Notas (campo abierto de texto)
- [ ] Link (campo abierto de texto)
- [x] Fotografía (campo de carga de archivo)2

**Comment by caom92** [comment]
Tengo varias preguntas:
1.  ¿estos datos para qué tipo de documento van a ser? ¿laboratorios, certificados, usda o todos?
2. ¿porqué necesita un campo de _link_ si se supone que ya estarían subiendo los archivos necesarios? ¿hay documentos que tengan asociados álbumes de fotos?

Además me gustaría hacer una observación: vi que escribió esto:
> Fotografía (campo de carga de archivo)2

Le recuerdo que habíamos quedado al final que sólo se subirían documentos PDF y así programé el sistema; si intenta capturar una imágen (no importa el formato), el sistema se lo va a rechazar

**Comment by caom92** [comment]
Debido a que realizar éste cambio implica agregar campos en varios de los formularios del sistema, su implementación incurrirá un costo **adicional** al de desarrollo equivalente a las horas que tome desarrollarlo.

**Comment by delcabo** [comment]
Tienes razon  "Laboratorio (campo abierto de texto)"  estan de forma indenpendiente!
y quitar el LINK :)

**Comment by delcabo** [comment]
el la parte de la FOTO cierto, sol poner una nota que diga "PDF"

**Comment by delcabo** [comment]
y quitar lo de "Solicitud de Estudio"

**Comment by caom92** [comment]
¿a qué se refiere con quitar "Solicitud de Estudio"?

**Comment by delcabo** [comment]
Este campo no lo recuerdo haber visto! sorry!!!  o si lo hice, veo que no sera necesario solo se requiere poner 1 solo donde guarde el archivo PDF y listo

**Comment by caom92** [comment]
El campo de solicitud fue porque me comentó desde el principio que laboratorios capturaban 2 documentos: primero uno que era el documento donde se mandaba a hacer el analisis y, días después, subirían un 2do documento que serían los resultados de dicho análisis. Por eso son 2 campos de documento. Si nomás lo dejo con 1 campo, tendrían que ustedes combinar ambos documentos en un sólo archivo PDF antes de subirlo.

**Comment by delcabo** [comment]
aah OK entiendo fue un malentendido... en si, asi es el proceso... pero no hay documento que tengmos que subir para el campo #1..  Realmente tendremos que esperar y capturar el registro hasta que llegue el resultado oficial o nos envien copia PDF del laboratorio...   esta bien eliminarlo por favor

**Comment by caom92** [comment]
Terminé de modificar la pantalla de captura y búsqueda para ambos tipos de documento, ahora estas pantallas se ven de la siguiente forma:

#### Captura de Certificados, USDA, etc.
![lol1](https://user-images.githubusercontent.com/9997614/31360147-f40e527c-ad01-11e7-9cd4-cb25b4be9319.png)

#### Captura de Laboratorios
![lol2](https://user-images.githubusercontent.com/9997614/31360153-fe73c224-ad01-11e7-817f-6c9eaaed4188.png)

#### Búsqueda de Certificados, USDA, etc.
![lol3](https://user-images.githubusercontent.com/9997614/31360167-0da93490-ad02-11e7-809e-c905156bb710.png)

#### Búsqueda de Laboratorios
![lol4](https://user-images.githubusercontent.com/9997614/31360206-30bfee38-ad02-11e7-8f83-1dafae718911.png)

#### Despliegue de documento para todos los tipos de archivo
![lol7](https://user-images.githubusercontent.com/9997614/31360249-55ff4bda-ad02-11e7-9155-12cda3525953.png)

**Comment by caom92** [comment]
[Tiempo total: 9.5 horas]

**Comment by caom92** [comment]
Debido a todos los cambios realizados en la BD, al implementar esta nueva versión en el servidor de Julio, será necesario reinstalar la BD, lo que provocará que todos los datos ahí almacenados se pierdan.

**Comment by delcabo** [comment]
buen dia!
Adelante. no hay datos reelevantes todavia!

saludos

**Comment by delcabo** [comment]
pregunta.... porque hay 2 Ranch???

**Comment by delcabo** [comment]
Zona (campo de tipo lista de selección, tomado de las Zonas guardadas en el
sistema)
• Productor (campo abierto de texto)1
• Producto o Área (campo abierto de texto)

**Comment by caom92** [comment]
Sólamente es un error en el desplegado de texto, ya lo corregí
