### ISSUE TITLE
CAptura de LABORATORIO equivoca y combo incompleto

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#20]
Cuando se captura un documento LABORATORIO
al momento de salvar cambia de TIPO de Analisis todos a MICROBIOLOGICOS PATOGENOS  por alguna razon
el primero fue captura  METALES PESADO
el 2do fue MULTIRRESIDUAL DE PLAGUICIDAS
y 3ro tambiensegun yo tambien le puse MULTIRRESIDUAL DE PLAGUICIDAS

![image](https://user-images.githubusercontent.com/28766240/32465582-d7996e26-c2f8-11e7-9a22-f6b5affe53f1.png)

y cuando seleccionar SUBTipo sale extrano el combo
![image](https://user-images.githubusercontent.com/28766240/32465552-b65c9044-c2f8-11e7-986e-7ae6b487ad8c.png)

**Comment by caom92** [comment]
Este es un problema que le comentaba el otro día de  que algunos navegadores web (como el Google Chrome que usa en esas imágenes) coloca un combo box encima del combo box programado en el sistema. **NO** utilice ese combo box, pues puede llevar a capturas equivocadas; si hace clic en la caja de texto y le aparece el combo box del navegador, simplemente precione la tecla ESC en su teclado y desaparecerá, permitiendo que sea visible el combo box del sistema. El combo box del sistema es distinguible porque tiene las letras de color verde azulado, mientras que las del navegador solo usa letras negras. Desafortunadamente, siendo una característica del navegador, no hay nada que nosotros podamos hacer para evitar ese problema; si le causa mucha molestia, le sugiero que modifique la configuración de su navegador para que ya no le aparezca ese combo box.
