### ISSUE TITLE
Lab - Captura - Código JS se congela tras manifestarse un error imprevisto (Firefox)

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#21]
Buscando como dar solucion a el detalle de Chrome sobre el mal manejo de combo, instale FIREFOX para probar el mismo captura de LABORAOTRIOS

parecia todo bien, pero no active el boton de ENVIAR

![image](https://user-images.githubusercontent.com/28766240/32630068-28d89bf0-c550-11e7-86a9-a5612188ed40.png)

**Comment by caom92** [comment]
Ya pude reproducir el problema, al parecer se debe a que Firefox interpreta nuestro código de forma diferente a Chrome, pero necesito hacer más pruebas para encontrar la causa exacta y arreglarlo. De cualquier forma, el problema de los combo box de Chrome debió arreglarse con la última actualización del sistema así que por lo pronto evite usar Firefox hasta que encontremos la solución al problema.

**Comment by caom92** [comment]
Al intentar reproducir el problema encontré que el servicio genera un error que dice "e.srcElement is undefined" con Firefox únicamente

**Comment by caom92** [comment]
Resulta que la propiedad srcElement del objeto event es propietario de IE y por ende no todos los navegadores lo soportan; la propiedad correcta es target
