### ISSUE TITLE
No salen opciones en combo de ZONA y PRODUCTO

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#22]
No hace el drop down de las opciones en estos 2 campos!
Falta el rango de Fechas...

![image](https://user-images.githubusercontent.com/28766240/32922702-65b94806-cae8-11e7-8059-01a56b88ccf3.png)

**Comment by caom92** [comment]
@delcabo  por favor absténgase de reportar errores de proyectos ajenos al que pertenece en éste repositorio. Para reportar errores del proyecto del Score Card, use [este enlace](https://github.com/caom92/qc-score-card/issues). 

Estamos buscando alternativas para ofrecerle en el futuro una plataforma integral donde pueda reportar problemas de cualquier proyecto y éstas se redireccionen al proyecto que les corresponde automáticamente, pero por ahora por favor esté atento sobre dónde está reportando sus errores. Gracias.
