### ISSUE TITLE
Encabezado para reporte PDF en QC Score

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#23]
Poner encabezado a nombre de JFDC

Jacobs Farm / Del Cabo
2450 STAGE RD. Pescadero, CA. 94060

![image](https://user-images.githubusercontent.com/28766240/32922744-96799f72-cae8-11e7-907e-5f8b1e8646fb.png)

**Comment by caom92** [comment]
@delcabo por favor absténgase de reportar errores de proyectos ajenos al que pertenece en éste repositorio. Para reportar errores del proyecto del Score Card, use [este enlace](https://github.com/caom92/qc-score-card/issues).

Estamos buscando alternativas para ofrecerle en el futuro una plataforma integral donde pueda reportar problemas de cualquier proyecto y éstas se redireccionen al proyecto que les corresponde automáticamente, pero por ahora por favor esté atento sobre dónde está reportando sus errores. Gracias.
