### ISSUE TITLE
Agregar mecanismo para controlar cuáles documentos capturados ya tienen su equivalente físico

### ISSUE THREAD

**Issue by caom92** [caom92/doc-manager#27]
Julio desea que el sistema posea un mecanismo para controlar cuáles de los documentos digitalizados en el sistema tienen su equivalente físico. Decidí que esto se logrará agregando un checkbox en la pantalla donde se despliega el PDF y que en la pantalla de búsueda, marque cuáles tienen ése checkbox indicado y cuáles no, además de desplegar la suma total de los documentos que sí tienen el checkbox activado, pero sólamente de los resultados obtenidos del intervalo de fechas ingresado.

**Comment by caom92** [comment]
Ya quedó implementado

![screenshot_2017-11-20_21-02-39](https://user-images.githubusercontent.com/9997614/33056646-a813f768-ce3b-11e7-9c9a-3ed824bd6cc3.png)

![screenshot_2017-11-20_21-41-23](https://user-images.githubusercontent.com/9997614/33056651-abecc112-ce3b-11e7-9f46-5346d7bfa29c.png)

**Comment by delcabo** [comment]
gracias Probando!

**Comment by delcabo** [comment]
crees que puedes cambiar el texto por:
"Es Documento Original?

**Comment by delcabo** [comment]
y en el titulo de busqueda o reporte que diga ORIGINAL

![image](https://user-images.githubusercontent.com/28766240/33139685-dd06ac40-cf62-11e7-85a2-6199c899ac11.png)

perfecto gracias!!!!
