### ISSUE TITLE
que despliegue los actuales antes de dar de alta, como las otras pantallas

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#29]
No sale la lista de UP actuales..

![image](https://user-images.githubusercontent.com/28766240/32972302-7185dd70-cba6-11e7-85a8-05c7c9d02912.png)

**Comment by caom92** [comment]
Las UP dependen de la zona, tiene que primero elegir una zona del combo box de un costado. Me acabo de dar cuenta de que le hace falta una etiqueta que diga **Zona**, se la agregaré tan pronto como pueda.

![screenshot_2017-11-17_16-51-13](https://user-images.githubusercontent.com/9997614/32974979-aaaa02d2-cbb7-11e7-99a0-5a405e2b06a8.png)
