### ISSUE TITLE
En la pantalla de búsqueda, permitir que se puedan buscar los documentos de todas las zonas

### ISSUE THREAD

**Issue by caom92** [caom92/doc-manager#3]
Julio dijo:
> Busqueda:
No pone por default todos, si solo quiero las fechas el resto de los campos por default "TODOS"

![31255697-04340ac4-a9e3-11e7-9fe3-8b776d6e61dc](https://user-images.githubusercontent.com/9997614/31258365-832e269c-a9f3-11e7-9705-b63202e4e3c6.png)

**Comment by caom92** [comment]
Este cambio **no** incurrirá un costo adicional debido a que fue reportado dentro del periódo de prueba

**Comment by caom92** [comment]
Después de analizar el problema e intentar resolverlo durante un rato, me dí cuenta de que este cambio está relacionado con #2 y por ende, también requiere modificar la base de datos y el comportamiento de ese formulario y sus reglas de validación. Debido a esto, la implementación de este cambio incurrirá un costo **adicional** al de desarrollo.

**Comment by delcabo** [comment]
buen dia!
Adelante vamos!

**Comment by caom92** [comment]
Así es como quedó implementado. Esta capacidad está presente en la pantalla de búsqueda para todos los tipos de documento (Laboratorios, Certificados, USDA, etc.). Puede elegir la opción que dice "TODOS" o simplemente no elegir ninguna opción y aún así el programa lo va a considerar como si hubiera elegido la opción "TODOS".

![kek1](https://user-images.githubusercontent.com/9997614/31412601-96ff8fdc-adca-11e7-96eb-6b0e62f3a61d.png)

![kek2](https://user-images.githubusercontent.com/9997614/31412603-9b8707ce-adca-11e7-8e5a-2aa1fc87385a.png)

Los campos para los cuáles puede elegir la opción de "TODOS" son:
##### Certificados, USDA, etc.
- Zonas
- Ranchos
- Productores
- Productos o Áreas

#### Laboratorios
- Los mismos que con **Certificados, USDA, etc.**
- Laboratorios

**Comment by caom92** [comment]
[Total de horas de desarrollo: 5.5]

**Comment by delcabo** [comment]
Carlitos lo unico que veo es todavia Ranchos o Productores.... me sobra 1 campo!!  RANCHOS...

**Comment by delcabo** [comment]
se puede eliminar por favor
