### ISSUE TITLE
en REPORTE que pueda selecionar solamente ZONA si uno quiere

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#31]
pero tambien  si quiere irse directo a las tipo y Sub tipo que diga primero (All)

![image](https://user-images.githubusercontent.com/28766240/33039384-a0c09682-cdec-11e7-9cbe-6f74ce036212.png)

![image](https://user-images.githubusercontent.com/28766240/33039490-f5c4c0e0-cdec-11e7-8225-610be0beee32.png)

**Comment by caom92** [comment]
Si hago eso, los datos no van a caber en el PDF. Así se mira el reporte PDF ahorita que sólo se puede elegir 1 subtipo únicamente:

![screenshot_2017-11-20_21-28-19](https://user-images.githubusercontent.com/9997614/33056368-19f84e58-ce3a-11e7-94c4-b28ca67c668c.png)

Como puede darse cuenta, son demasiadas Unidades de Producción que no caben en el documento, tuve que dividirlo en varios renglones. Eso es únicamente viendo los datos de AGUA. Ahora imagine que selecciona TODOS los tipos y TODOS los subtipos. Voy a tener que mostrar los datos de cada subtipo así como los ve en esa imagen. Puedo implementar el cambio, pero así va a quedar el PDF y no se va poder cambiar, ¿desea que lo implemente de todas formas?

**Comment by delcabo** [comment]
Buen dia!

Se puede invertir los datos??

UP de forma vertical

![image](https://user-images.githubusercontent.com/28766240/33082860-acbb872a-ce92-11e7-97fb-9f7eec8273b2.png)

**Comment by caom92** [comment]
¿Qué le parece así? 

![screenshot_2017-11-22_15-46-41](https://user-images.githubusercontent.com/9997614/33154517-b20e0c50-cf9d-11e7-99a5-33ba8840dd0b.png)

![screenshot_2017-11-22_15-52-26](https://user-images.githubusercontent.com/9997614/33154521-b857e9be-cf9d-11e7-81cb-872484d2de0d.png)

**Comment by delcabo** [comment]
3 peticiones mas! para este reporte
1.-  Toma por default los datos de AVA en el header...  tal vez que tome el de la ZONA que se selecciono primero....
2.-  Se puede colorear de NEGRO y letras blancas "Tipo de Analisis"
3.-  se puede Totalizar cada columna???

![image](https://user-images.githubusercontent.com/28766240/33188596-0e49ad00-d050-11e7-926f-ef1d30d3dc6f.png)

**Comment by delcabo** [comment]
upps  volvio a salir GRupo VAllecitos en el reporte que seleccione como zona BCN

![image](https://user-images.githubusercontent.com/28766240/33220241-724e3216-d0fb-11e7-934c-cae95a7a4047.png)

**Comment by delcabo** [comment]
y faltarian los demas tipos de analisis, de acuerdo!

![image](https://user-images.githubusercontent.com/28766240/33220280-c42c9d70-d0fb-11e7-9cd2-e3683cd019b3.png)
