### ISSUE TITLE
Dar de alta LABORATORIO

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#32]
Al momento de dar de alta laboratorio, se da enviar "Primus Labs"  pero no sale en la lista
sali y volvi a entrar y nada!

![image](https://user-images.githubusercontent.com/28766240/33219080-4106bb52-d0f5-11e7-8764-9b2b81a1ea1d.png)

**Comment by caom92** [comment]
Ya quedó arreglado y capturado

![screenshot_2017-01-12_12-38-25](https://user-images.githubusercontent.com/9997614/33290446-8e2180aa-d377-11e7-9514-34e75f10c78f.png)
