### ISSUE TITLE
Dar de alta "UP" en SSF

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#33]
al momento de dar de alta un "Organic Harvest LLC" me manda error

![image](https://user-images.githubusercontent.com/28766240/33219136-950fbd8e-d0f5-11e7-9355-4c7f7fa3a1d6.png)

**Comment by caom92** [comment]
Era un error con el servicio de captura, ya quedó solucionado. Puede intentar capturar de nuevo y debería funcionar esta vez.
