### ISSUE TITLE
Titulo de otra zona!

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#34]
Todavia sale el emcabezado a AVA cuando debe ser datos de BCN.

![image](https://user-images.githubusercontent.com/28766240/33456633-d2c3d1a4-d5d4-11e7-8695-4ab669a7cded.png)

**Comment by caom92** [comment]
Necesito que me diga cuál usuario utilizó para poder intentar replicar el problema.

**Comment by caom92** [comment]
Ya quedó arreglado, era un problema con el usuario de rol de Director, donde no estaba actualizando la información de la zona cuando el usuario cambiaba de zona. 

![screenshot_2017-12-01_13-22-38](https://user-images.githubusercontent.com/9997614/33504096-f7f7feac-d69a-11e7-90b1-8917f950ff17.png)
