### ISSUE TITLE
Cambio de letero en LAB

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#35]
Buen dia!

se puede cambiar un texto o letrero

"Fecha de Documento/Document Date" x "Fecha de Muestreo/Sample Test Date"

![image](https://user-images.githubusercontent.com/28766240/34629087-bb184d88-f21b-11e7-8bb8-9f8a2b19266d.png)

**Comment by caom92** [comment]
Ya quedó implementado, el cambio se veerá reflejado en la próxima actualización
