### ISSUE TITLE
No SUB-tipos en busqueda 

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#37]
tardes!!

no salieron las opciones que corresponan a Microbiologico en busqueda de analisis...

![image](https://user-images.githubusercontent.com/28766240/35014675-5f5fe128-fac6-11e7-98ff-d2023456ee15.png)

**Comment by caom92** [comment]
No pude replicar el problema, ¿con qué usuario intentó hacer la búsqueda?

**Comment by VMiracle** [comment]
Cerré este issue puesto que no fue replicable, en caso que vuelva a surgir, tanto un nuevo issue como reabrir este es posible
