### ISSUE TITLE
En REPORTES  no me sale SSF

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#39]
tratando de sacar un reporte de rango de fechas grandes, no me sale nada... 
pero si sale en busquedas!!

![image](https://user-images.githubusercontent.com/28766240/35059068-c5cf3802-fb6e-11e7-8e06-76a1050e1cd9.png)

**Comment by caom92** [comment]
Ya quedó arreglado, era un problema donde no se estaba mandando la zona correcta para generar el reporte

![screenshot_2018-01-17_11-05-29](https://user-images.githubusercontent.com/9997614/35061554-6cb5c9ea-fb76-11e7-9a6a-3ecbd5a392db.png)
