### ISSUE TITLE
Desplegar info adicional en la lista de archivos encontrados al realizar una búsqueda

### ISSUE THREAD

**Issue by caom92** [caom92/doc-manager#4]
Julio dijo: 
> Puede poner mas informacion una vez que encuentre registros, tal vez Productor-producto/Area :)

![31255741-3eb55644-a9e3-11e7-90e4-7459fa39b52a](https://user-images.githubusercontent.com/9997614/31258392-c643e69c-a9f3-11e7-833b-f83aabd5d05b.png)

**Comment by caom92** [comment]
Mientras la info que quiere que se muestre en esta lista sea la misma para USDA y Certificados, no va a haber problema, pero si quiere que para USDA se despliegue info diferente a Certificados, voy a tener que reescribir mucho código y me tomará mucho tiempo.

**Comment by caom92** [comment]
Debido a que éste cambio depende de la implementación del cambio solicitado en #2 , la implementación de éste cambio incurrirá un costo *adicional* al de desarrollo equivalente a las horas que tome implementarlo

**Comment by delcabo** [comment]
OK, esta bien favor de considerar a proceder el ajuste..

**Comment by caom92** [comment]
En esta pantalla ahora se muestra información más detallada, para todos los documentos

![kek](https://user-images.githubusercontent.com/9997614/31365897-0ff4877e-ad23-11e7-8861-da7ac3a6ce0b.png)

**Comment by caom92** [comment]
[Total de tiempo de desarrollo: 3 horas]

**Comment by caom92** [comment]
Decidí cambiar la forma en que se presenta la info de tarjetas a una tabla para probar cuál se mira mejor. Por lo pronto lo dejare en forma de tabla, pero si desean revertirlo a forma de tarjetas, dejé el código preparado para hacerlo.

![kek](https://user-images.githubusercontent.com/9997614/31400255-c767aca8-ada3-11e7-9eaa-b26a1fa77c0e.png)

**Comment by delcabo** [comment]
nice....! :)
