### ISSUE TITLE
pantalleo extrano

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#40]
cuando entro a una captura de documentos (LAB o cualquier otro)
si le doy Back, no se sale pero si le doy ESC se sale correctamente me aparece la pantalla de usuario activo pero sin menu de LAB

![image](https://user-images.githubusercontent.com/28766240/35594998-0af1aaae-05ca-11e8-9dd5-c5ea6d8b0fa4.png)

**Comment by caom92** [comment]
No pude reproducir el problema siguiendo los pasos que me proveyó
