### ISSUE TITLE
SOP  ajuste en reporte (busqueda)

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#41]
Si es posible poner el texto de  NOTAS o COMENTARIOS en el resultado. 
algo asi
![image](https://user-images.githubusercontent.com/28766240/35750110-bf001d56-0808-11e8-913d-1cc3ab259768.png)

**Comment by caom92** [comment]
Víctor me comentó que el problema que tenian era que necesitaban poder ponerle un nombre al documento para poder diferenciarlo de los demás, así que agregué un campo en el formulario de captura para ingresar el nombre del documento y este es el campo que se muestra en la lista de resultados de búsqueda. De esta forma no tienen que colocar el nombre del documento en la sección de comentarios. 

![screenshot_2018-02-19_16-41-00](https://user-images.githubusercontent.com/9997614/36402476-b1294ff2-1593-11e8-8909-9c275111d01b.png)

Los cambios se veerán reflejados en el servidor de Julio en la próxima actualización.
