### ISSUE TITLE
pantalleo raro!!

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#44]
cuando hice una busqueda, abri el documento y regreso
le di BACK y me salio esta pantalla

![image](https://user-images.githubusercontent.com/28766240/35886492-109c62ec-0b46-11e8-82b5-a435752eedfb.png)

**Comment by caom92** [comment]
No pude reproducirlo, posiblemente estaba relacionado con otro error que ya quedó arreglado.
