### ISSUE TITLE
Forma de seleccion de fechas en reportes y busquedas

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#47]
si es posible que se cambie el metodo o formato de fechas en reportes, busquedas o consultas
![image](https://user-images.githubusercontent.com/28766240/36285367-211ed9f8-1260-11e8-809b-4087ac7ce324.png)

**Comment by caom92** [comment]
Ya quedó implementado, los cambios se veeran reflejados en el servidor de Julio en la próxima actualización
