### ISSUE TITLE
El boton de VIEW esta desactivado !!!

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#48]
Buen dia al momento de hacer una consulta de LABORATORIO, el botton de VIEW no hace nada.
los demas opciones (SOP y Cartas) estan bien!

![image](https://user-images.githubusercontent.com/28766240/37104183-e6f1f9a0-21e0-11e8-9ae6-dff9d105675a.png)

**Comment by caom92** [comment]
Ya quedó corregido y los cambios ya están en su servidor.
