### ISSUE TITLE
Laboratorio-Buscar  

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#6]
el primer Campo RANCHO lo use para tipo de laboratorio...  se puede ajustar por favor a "Tipo Analisis"
![image](https://user-images.githubusercontent.com/28766240/31415269-2a015048-add7-11e7-8ff0-1bb2aa7d9c63.png)

**Comment by caom92** [comment]
Va a necesitar el campo de rancho todavia o quiere que lo remueva?

**Comment by delcabo** [comment]
se puede cambiar el titulo a "Tipo de Analisis"?   y listo con este

**Comment by caom92** [comment]
El detalle es que, como expliqué en #10, hay una dependencia jerárquica lineal entre las zonas, los ranchos, los productores y las áreas o productos, no es simplemente cambiar el titulo, porque el rancho depende de la zona y el productor depende del rancho. Esto afecta la forma en la que se buscan los registros en la base de datos. Si solamente le cambio el título, este funcionamiento permanecerá. Si bien es verdad que puede utilizar ese campo para capturar los tipos de análisis, **NO** podrá hacer búsquedas por análisis, porque contará como si fuera un rancho. Para tener ese comportamiento, se necesita agregar ese campo en el formulario y hacer las modificaciones correspondientes en la base de datos.

**Comment by delcabo** [comment]
Ok entoces quitar x fas

**Comment by caom92** [comment]
No se puede quitar el campo de rancho porque entonces se tendría que remover el campo de área o productor. Voy a ponerle el campo de tipo de análisis como un campo adicional al de rancho.

**Comment by delcabo** [comment]
OK Carlos

**Comment by caom92** [comment]
Así quedó el formulario de captura de laboratorios con el campo de tipo de analisis ingresado:
![kek1](https://user-images.githubusercontent.com/9997614/31515388-ddf75494-af49-11e7-9914-a2697ee497f1.png)

Y así se ve al realizar una búsqueda:
![kek2](https://user-images.githubusercontent.com/9997614/31515401-e91328d0-af49-11e7-841b-a2cc91724905.png)

![kek3](https://user-images.githubusercontent.com/9997614/31515403-ec2e6ba6-af49-11e7-85ed-fd7ed74c22cb.png)

**Comment by caom92** [comment]
La implementación de este cambio entra dentro de la cláusula **"Costo de integración de requerimientos adicionales"**, en el punto que dice:
> Agregar funcionamiento específico a un tipo de documento determinado (8 a 16 horas,
dependiendo de la dificultad): si se desea agregar algún funcionamiento específico
que se aplique a alguno de los tipos de documentos existentes (similar a como fue el
caso de laboratorios, donde se necesita asociar un resultado con su solicitud).

y por lo tanto se cobrará acorde al precio estipulado en ésta cláusula.

**Comment by delcabo** [comment]
Dato Curioso

se captura "Superficies Vivas" en el campo Rancho
y salio en el reporte "Microbiologico Patogeno"

**Comment by delcabo** [comment]
![image](https://user-images.githubusercontent.com/28766240/31520251-1bec58ca-af5a-11e7-991a-2d481b39dea9.png)
![image](https://user-images.githubusercontent.com/28766240/31520265-27abb1b0-af5a-11e7-9379-950a5f6a8af6.png)
