### ISSUE TITLE
Laboratorio - Abrir PDF

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#7]
Cuando abro el link para ver PDF, se ve muy bien, pero un back no regresa realmente al resultado de busqueda, se vuelve a cargar la pagina PDF de nuevo
![image](https://user-images.githubusercontent.com/28766240/31415301-62172fa2-add7-11e7-8fac-a6319e3a1e2b.png)

**Comment by delcabo** [comment]
aaah perdoin ya vi el BOTON regresar, pero la verdad no se ve de primera instancia!! 
se puede hacer algo para que se vea, esta muy ligero

**Comment by delcabo** [comment]
si no.. no problema es question de ajustar vista!!!

**Comment by caom92** [comment]
Eso ocurre porque al abrir el documento no está navegando a otra página sino que permanece en la misma, pero se despliega una ventana encima que es la que carga el PDF. Por eso, al hacer clic en el botón de regresar, éste lo navegará a la página en la que se encontraba antes de realizar la búsqueda. Para regresar a la lista de resultados, debe hacer clic en el botón de cerrar. No se puede hacer nada para hacer el botón más visible, su comportamiento es fijo, sólo se le puede cambiar el color. Tampoco hay nada que se pueda hacer para que al hacer clic en el botón de Atrás del navegador, lo regrese a la lista de resultados de búsqueda, porque esta lista no se almacena en memoria; se recupera de la base de datos. Si usted navega a otra página, la lista se perderá y tendrá que realizar la búsqueda de nuevo, es por eso que decidí utilizar una ventana que cubre la página para desplegar el documento PDF (porque, como mencioné anteriormente, desplegar esa ventana no implica una navegación a una página diferente y por ende la lista de resultados de búsqueda permanece en la página).

**Comment by delcabo** [comment]
OK perfecto lo puedes poner de ROJO jajjajaja y listo
