### ISSUE TITLE
Laboratorio - Borrar registro

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#8]
Es posible tener esta opcion en la busqueda???  Eliminar un registro?

**Comment by caom92** [comment]
Si pero no podría recuperarse una vez borrado

**Comment by delcabo** [comment]
asi es, perfecto...

**Comment by caom92** [comment]
Terminé de implementar el borrado de documentos, para todos los tipos de documento.

Nótese cómo tuve que revertir la forma de presentar la lista de resultados de búsqueda de tabla a tarjetas. Esto es porque con el botón de borrado ya eran demasiadas columnas y no se podía ver bien toda la info.
![kek1](https://user-images.githubusercontent.com/9997614/31479994-0b5ff7ee-aed0-11e7-9f59-bacaa883c804.png)

Antes de borrar el documento, implementé una pantalla que pide confirmación antes de continuar.
![kek2](https://user-images.githubusercontent.com/9997614/31480037-406f7dec-aed0-11e7-9d30-4fbad567bf9d.png)

Después de borrar el documento, se remueve de la lista de resultados de búsqueda.
![kek3](https://user-images.githubusercontent.com/9997614/31480047-4fabe52a-aed0-11e7-9053-8049710cba54.png)

**Comment by caom92** [comment]
[Total de horas necesarias para el desarrollo: 5.5]

**EDIT**: decidí reducir el tiempo de horas necesarias porque la mayor cantidad de ese tiempo fue para depurar un error en el código que resulto ser algo sumamente obvio pero oculto a simple vista. Debido a que después de corregir ese pequeño error (que básicamente implicaba una letra de más en una línea del código) el borrado funcionó perfectamente, no me parece justo cobrar tantas horas en detectar un error tan bobo, _al menos en esta ocasión_.

**Comment by delcabo** [comment]
Enterado Carlos, ya esta arriba?
