### ISSUE TITLE
Laboratorio - Quien y quien no

### ISSUE THREAD

**Issue by delcabo** [caom92/doc-manager#9]
Se puede hacer que solo a nivel Supervisor o mas alto nivel se puede tener acceso a este Modulo?

Creo que Empelado seria el unico en no tener Acceso a este modulo!!!

**Comment by caom92** [comment]
Necesitamos hablar al respecto en persona para discutirlo, porque hay muchos detalles que ver con esto y que debemos ponernos de acuerdo.

**Comment by delcabo** [comment]
perfecto sera el martes en la visita...
